spring:
  datasource:
    ##url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/example?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
mybatis:
  mapperLocations: classpath:/mapper/*.xml

zookeeper:
  address: 127.0.0.1:2181
  timeout: 4000
logging:
  config: src/main/resources/log4j.properties